default_icon: "root_icon.png"
default_avata: "/assets/user-default.png"
icon_size: "70x70"
size_of_book_cover: "200x300"
min_size_of_book_cover: "100x150"
default_book_conver: "default-book-cover.jpg"
avatar_size: "130x130"
avatar_min_size: "70x70"
avatar_header_size: "60x60"
default_rate: 1
max_lenght_title: 70
max_lenght_name: 50
max_lenght_email: 255
min_lenght_password: 6
max_lenght_book_introduce: 10000
max_lenght_name_of_book: 255
max_lenght_content_comment: 1000
max_lenght_request_description: 1000
max_length_password: 100
max_length_review_title: 255
max_length_review_content: 100000
max_rate: 5
length_sub_introduce: 255
length_sub_title: 40
true: "true"
per_page_comments: 10
per_page_user: 12
per_page_search: 12
book:
  per_page_review: 12
  per_page_book: 12
user:
  user_per_page: 12
  activities_per_page: 10
  size_of_book_cover: "66x95"
